account/urls.py
# -*- coding: utf-8 -*-
"""
 @Time    : 2019/3/3 16:12
 @Author  : CyanZoy
 @File    : urls.py
 @Software: PyCharm
 """
from django.conf.urls import url
from . import views

app_name = "account"

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(success_url='/'), name='login'),
    url(r'^auth/qq/$', views.qq_login),
    # url(r'^register/$', views.RegisterView.as_view(success_url="/"), name='register'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout')
]

xadmin/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve

from xadmin.settings import MEDIA_ROOT

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('app_admin.urls')),
    url(r'', include('account.urls', namespace='accounts')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
]

templates/index.html
{% extends 'base/frame.html' %}
{% block content %}
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-3">
                <div class="ibox ">
                    <div class="ibox-title">
                        <span class="label label-success float-right">月度</span>
                        <h5>日志</h5>
                    </div>
                    <div class="ibox-content">
                        <h1 class="no-margins">40 886,200</h1>
                        <div class="stat-percent font-bold text-success">98% <i class="fa fa-bolt"></i></div>
                        <small>日志数</small>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="ibox ">
                    <div class="ibox-title">
{#                        <span class="label label-info float-right"></span>#}
                        <h5>分类</h5>
                    </div>
                    <div class="ibox-content">
                        <h1 class="no-margins">275,800</h1>
                        <div class="stat-percent font-bold text-info">20% <i class="fa fa-level-up"></i></div>
                        <small>类别数量</small>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="col-sm-4">
                <h1 class="m-b-xs">
                    26,900
                </h1>
                <small>
                    Sales in current month
                </small>
                <div id="sparkline1" class="m-b-sm"></div>
                <div class="row">
                    <div class="col-4">
                        <small class="stats-label">Pages / Visit</small>
                        <h4>236 321.80</h4>
                    </div>

                    <div class="col-4">
                        <small class="stats-label">% New Visits</small>
                        <h4>46.11%</h4>
                    </div>
                    <div class="col-4">
                        <small class="stats-label">Last week</small>
                        <h4>432.021</h4>
                    </div>
                </div>

            </div>
            <div class="col-sm-4">
                <h1 class="m-b-xs">
                    98,100
                </h1>
                <small>
                    Sales in last 24h
                </small>
                <div id="sparkline2" class="m-b-sm"></div>
                <div class="row">
                    <div class="col-4">
                        <small class="stats-label">Pages / Visit</small>
                        <h4>166 781.80</h4>
                    </div>

                    <div class="col-4">
                        <small class="stats-label">% New Visits</small>
                        <h4>22.45%</h4>
                    </div>
                    <div class="col-4">
                        <small class="stats-label">Last week</small>
                        <h4>862.044</h4>
                    </div>
                </div>


            </div>
            <div class="col-sm-4">

                <div class="row m-t-xs">
                    <div class="col-6">
                        <h5 class="m-b-xs">Income last month</h5>
                        <h1 class="no-margins">160,000</h1>
                        <div class="font-bold text-navy">98% <i class="fa fa-bolt"></i></div>
                    </div>
                    <div class="col-6">
                        <h5 class="m-b-xs">Sals current year</h5>
                        <h1 class="no-margins">42,120</h1>
                        <div class="font-bold text-navy">98% <i class="fa fa-bolt"></i></div>
                    </div>
                </div>


                <table class="table small m-t-sm">
                    <tbody>
                    <tr>
                        <td>
                            <strong>142</strong> Projects

                        </td>
                        <td>
                            <strong>22</strong> Messages
                        </td>

                    </tr>
                    <tr>
                        <td>
                            <strong>61</strong> Comments
                        </td>
                        <td>
                            <strong>54</strong> Articles
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>154</strong> Companies
                        </td>
                        <td>
                            <strong>32</strong> Clients
                        </td>
                    </tr>
                    </tbody>
                </table>


            </div>

        </div>
    </div>
{% endblock %}
{% block CustomJs %}

    <script>
        $(document).ready(function() {

            var sparklineCharts = function(){
                $("#sparkline1").sparkline([34, 43, 43, 35, 44, 32, 44, 52], {
                    type: 'line',
                    width: '100%',
                    height: '50',
                    lineColor: '#1ab394',
                    fillColor: "transparent"
                });

                $("#sparkline2").sparkline([32, 11, 25, 37, 41, 32, 34, 42], {
                    type: 'line',
                    width: '100%',
                    height: '50',
                    lineColor: '#1ab394',
                    fillColor: "transparent"
                });

                $("#sparkline3").sparkline([34, 22, 24, 41, 10, 18, 16,8], {
                    type: 'line',
                    width: '100%',
                    height: '50',
                    lineColor: '#1C84C6',
                    fillColor: "transparent"
                });
            };

            var sparkResize;

            $(window).resize(function(e) {
                clearTimeout(sparkResize);
                sparkResize = setTimeout(sparklineCharts, 500);
            });

            sparklineCharts();

            var data1 = [
                [0,4],[1,8],[2,5],[3,10],[4,4],[5,16],[6,5],[7,11],[8,6],[9,11],[10,20],[11,10],[12,13],[13,4],[14,7],[15,8],[16,12]
            ];
            var data2 = [
                [0,0],[1,2],[2,7],[3,4],[4,11],[5,4],[6,2],[7,5],[8,11],[9,5],[10,4],[11,1],[12,5],[13,2],[14,5],[15,2],[16,0]
            ];
            $("#flot-dashboard5-chart").length && $.plot($("#flot-dashboard5-chart"), [
                        data1,  data2
                    ],
                    {
                        series: {
                            lines: {
                                show: false,
                                fill: true
                            },
                            splines: {
                                show: true,
                                tension: 0.4,
                                lineWidth: 1,
                                fill: 0.4
                            },
                            points: {
                                radius: 0,
                                show: true
                            },
                            shadowSize: 2
                        },
                        grid: {
                            hoverable: true,
                            clickable: true,

                            borderWidth: 2,
                            color: 'transparent'
                        },
                        colors: ["#1ab394", "#1C84C6"],
                        xaxis:{
                        },
                        yaxis: {
                        },
                        tooltip: false
                    }
            );

        });
    </script>

{% endblock %}

templates/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MAOA | Login</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://at.alicdn.com/t/font_1074635_d9qebc8pagi.css">
    <style>
        .errorlist li{
            list-style-type: none;
            color: #a94442;
            background-color: #f2dede;
            border-color: #ebccd1;
            border-radius: 5px;
            padding: 10px 15px;
        }
        ul{
            padding: 0;
        }
    </style>
</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">MA</h1>

            </div>
{#            <h3>Welcome to MA+</h3>#}
            <p>
                <!--Continually expanded and constantly improved Inspinia Admin Them (IN+)-->
            </p>
            <p>登录</p>
            <form class="m-t" role="form" action="{% url 'account:login' %}" method="post">
                {% csrf_token %}
                {% autoescape off %}
                {{ form.non_field_errors }}
                {% endautoescape %}
                {% for field in form %}
                    <div class="form-group">
                    {{ field }}
                    {{ field.errors }}
                    </div>
                {% endfor %}

                <input type="hidden" name="next" value="{{ redirect_to }}">

{#                <div class="form-group">#}
{#                    <input name="username" type="text" class="form-control" placeholder="Username" required="">#}
{#                </div>#}
{#                <div class="form-group">#}
{#                    <input name="password" type="password" class="form-control" placeholder="Password" required="">#}
{#                </div>#}
                <button type="submit" class="btn btn-primary block full-width m-b">登录</button>
                <div class="text-danger">{{ loginError }}</div>
{#                <a href="#"><small>忘记密码?</small></a>#}
{#                <p class="text-muted text-center"><small>没有账户?</small></p>#}
{#                <a class="btn btn-sm btn-white btn-block" href="register.html">创建一个</a>#}
                <a href="https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=101548919&redirect_uri=http://www.cyanzoy.top/auth/qq&scope=get_user_info,list_album"><i class="iconfont icon-ic_tencent_qq" style="font-size: 32px;"></i></a>
            </form>
            <p class="m-t"> <small></small> </p>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %} "></script>
    <script src="{% static 'js/bootstrap.js' %} "></script>

</body>

</html>